#Workflow name
name: Python application

# Event specification
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Instalação de Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt;
    - name: Execução de Teste de unidades
      run: |
        python -m unittest src.tests.model_test